In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_validate,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import metrics, svm
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn import tree
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, RandomForestRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.cluster import KMeans, DBSCAN
from sklearn.feature_selection import chi2, SelectKBest, SelectFdr
from sklearn.decomposition import PCA
from scipy.cluster.hierarchy import dendrogram, linkage
from rake_nltk import Rake

Import data as data frame

In [41]:
data = pd.read_csv('problem_pdsm_simpleclean.csv')
data

Number  Priority      Business service        Category  \
0     63212         5                Server        Hardware   
1     63210         5              Computer        Hardware   
2     63205         5                Switch         Network   
3     63204         5                Server        Hardware   
4     63201         5                Switch         Network   
5     63200         3              Computer     Application   
6     63195         5                Switch         Network   
7     63194         3                Switch         Network   
8     63187         2              Computer        Hardware   
9     63173         5               Scanner        Hardware   
10    63158         5              Computer        Hardware   
11    63146         5                 Other         Network   
12    63145         3                Server        Hardware   
13    63144         5               Scanner     Application   
14    63143         5                 Other         Network   
15    63142         3                 Other         Network   
16    63141         4                 Other        Hardware   
17    63140         5                Switch         Network   
18    63139         5  Communication Device         Network   
19    63132         3                 Other         Network   
20    63125         3                Server     Application   
21    63124         5                Server     Application   
22    63121         5              Database        Hardware   
23    63117         5               Scanner        Hardware   
24    63113         3               Scanner        Hardware   
25    63107         5                 Other     Application   
26    63106         5                 Other     Application   
27    63105         2                Server     Application   
28    63101         5               Scanner        Hardware   
29    63098         3                Server     Application   
..      ...       ...                   ...             ...   
658   60142         5                Server     Application   
659   60141         5               Scanner     Application   
660   60137         5                Server     Application   
661   60136         5                Server     Application   
662   60135         5                Server     Application   
663   60123         5                Server     Application   
664   60121         5               Network     Application   
665   60120         5                Server        Hardware   
666   60117         4                Server     Application   
667   60086         5                Server     Application   
668   60085         5               Network        Hardware   
669   60084         5  Communication Device        Hardware   
670   60075         5  Communication Device  Inquiry / Help   
671   60064         5              Computer     Application   
672   60054         5                Server     Application   
673   60053         5              Database     Application   
674   60050         5              Database     Application   
675   60048         2               Network     Application   
676   60045         5              Computer     Application   
677   60044         5                Server     Application   
678   60042         5              Computer     Application   
679   60041         5               Network     Application   
680   60040         3                Server     Application   
681   60038         5  Communication Device     Application   
682   60037         4               Network        Hardware   
683   60030         5              Database     Application   
684   60029         5              Database     Application   
685   60026         5              Database     Application   
686   60019         5               Scanner        Hardware   
687   60003         5  Communication Device        Hardware   

                Company              Created Created Time  Created by  Impact  \
0        FedEx Se

## Set up for modeling

### Split up dependent and independent variables and get dummy variables for categorical features

In [3]:
data = data.drop(['Created', 'Duration Max', 'Duration Min', 'Duration Range',
                  'Short description', 'Keywords'], axis=1)
data.dtypes

Number                 int64
Priority               int64
Business service      object
Category              object
Company               object
Created Time          object
Created by             int64
Impact                 int64
Major Problem           bool
Problem Manager       object
Related Incidents      int64
Type                  object
Urgency                int64
Incidents Count        int64
Assignment group      object
Duration Mean        float64
Has Parent              bool
dtype: object

In [4]:
data = data.set_index('Number')
data.shape

(688, 16)

In [23]:
X = pd.get_dummies(data.drop('Category', axis=1))
X_df = pd.get_dummies(data.drop('Category', axis=1))
feature_list = list(X.columns)
X = X.values
X

array([[5, 5163721, 3, ..., 0, 0, 1],
       [5, 5163721, 3, ..., 0, 0, 1],
       [5, 3667964, 3, ..., 0, 0, 0],
       ...,
       [5, 5305519, 3, ..., 0, 0, 1],
       [5, 483039, 3, ..., 0, 0, 1],
       [5, 572652, 3, ..., 0, 0, 1]], dtype=object)

In [6]:
le = preprocessing.LabelEncoder()
# for col in range(len(X[0])):
#     X[:,col] = le.fit_transform(X[:,col])

In [7]:
y = data['Category'].values
y

array(['Hardware', 'Hardware', 'Network', 'Hardware', 'Network',
       'Application', 'Network', 'Network', 'Hardware', 'Hardware',
       'Hardware', 'Network', 'Hardware', 'Application', 'Network',
       'Network', 'Hardware', 'Network', 'Network', 'Network',
       'Application', 'Application', 'Hardware', 'Hardware', 'Hardware',
       'Application', 'Application', 'Application', 'Hardware',
       'Application', 'Application', 'Application', 'Application',
       'Hardware', 'Application', 'Telephony', 'Network', 'Network',
       'Application', 'Hardware', 'Hardware', 'Network', 'Hardware',
       'Hardware', 'Application', 'Hardware', 'Hardware', 'Application',
       'Application', 'Application', 'Hardware', 'Application', 'Network',
       'Application', 'Hardware', 'Application', 'Hardware',
       'Application', 'Application', 'Hardware', 'Hardware',
       'Application', 'Application', 'Application', 'Hardware',
       'Hardware', 'Hardware', 'Application', 'Application',

In [8]:
labeldict = dict(zip(le.fit_transform(y), y))
# labeldict
y = le.fit_transform(y)
y

array([2, 2, 5, 2, 5, 0, 5, 5, 2, 2, 2, 5, 2, 0, 5, 5, 2, 5, 5, 5, 0, 0,
       2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 7, 5, 5, 0, 2, 2, 5, 2, 2,
       0, 2, 2, 0, 0, 0, 2, 0, 5, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2,
       2, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 2, 5,
       5, 0, 0, 2, 0, 0, 3, 5, 0, 5, 0, 0, 0, 0, 0, 0, 5, 3, 5, 3, 3, 0,
       2, 0, 0, 0, 2, 0, 5, 3, 5, 0, 0, 0, 6, 3, 0, 0, 3, 2, 0, 2, 2, 0,
       2, 0, 2, 0, 3, 0, 0, 0, 5, 0, 2, 5, 0, 2, 0, 2, 5, 2, 0, 0, 5, 0,
       3, 0, 5, 5, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 3, 0, 0, 0, 0, 2, 2,
       5, 3, 2, 0, 0, 0, 3, 0, 0, 0, 2, 0, 2, 0, 2, 2, 3, 2, 0, 0, 0, 2,
       0, 7, 0, 0, 0, 0, 0, 0, 0, 5, 3, 0, 0, 3, 5, 7, 0, 0, 0, 5, 2, 0,
       0, 0, 0, 0, 0, 5, 0, 0, 4, 2, 0, 5, 0, 5, 2, 0, 0, 6, 6, 7, 0, 0,
       3, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 2, 6, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 2, 0, 0, 6, 0, 4, 0, 0, 0,
       0, 6, 0, 0, 0, 0, 6, 0, 0, 0, 6, 0, 4, 6, 0,

## Model using K-means

In [29]:
model = KMeans(n_clusters=8)
model.fit(X_df)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=8, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [ ]:
# smallX = X.drop('Created', axis=1)

In [ ]:
model = KMeans(n_clusters=8)
model.fit(smallX)

In [30]:
data['kmeans'] = model.labels_

In [33]:
metrics.adjusted_rand_score(data['Category'],data['kmeans'])

-0.02662341361869613

In [34]:
pca = PCA()
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [35]:
pca.explained_variance_ratio_

array([7.72702592e-01, 2.27297408e-01, 7.60421708e-13, 3.87265621e-13,
       2.75892879e-13, 2.61860223e-13, 7.91508927e-14, 6.82742726e-14,
       6.02135331e-14, 5.48786110e-14, 5.31515674e-14, 5.02539575e-14,
       4.49665394e-14, 4.09177693e-14, 3.43518806e-14, 3.12427751e-14,
       2.71722751e-14, 2.46325157e-14, 2.26646733e-14, 2.18352142e-14,
       1.98607886e-14, 1.88604316e-14, 1.68159711e-14, 1.62565198e-14,
       1.51024215e-14, 1.47511190e-14, 1.25082958e-14, 1.24127337e-14,
       1.18378433e-14, 9.53320188e-15, 8.03356200e-15, 7.73231817e-15,
       6.87291262e-15, 6.31965335e-15, 5.54390311e-15, 4.79564213e-15,
       4.63148089e-15, 4.18326853e-15, 3.68869411e-15, 3.55650818e-15,
       3.32181036e-15, 3.19688741e-15, 3.07322192e-15, 2.85820304e-15,
       2.64383023e-15, 2.08172553e-15, 1.87682762e-15, 1.59251896e-15,
       4.73512907e-16, 7.64971724e-33, 7.64971724e-33, 7.64971724e-33,
       7.64971724e-33, 7.64971724e-33, 7.64971724e-33, 8.43623662e-37])

In [36]:
pca = PCA(n_components=2)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [37]:
pca.explained_variance_ratio_

array([0.77270259, 0.22729741])

In [27]:
transformed = pca.transform(X_df)

ValueError: operands could not be broadcast together with shapes (688,56) (2,) 

In [40]:
pca = PCA(n_components=2)
pca.fit_transform(X_df)

# Dump components relations with features:
pd.DataFrame(pca.components_,columns=X_df.columns,index = ['PC-1','PC-2']).iloc[0]

Priority                                      -3.430419e-09
Created by                                    -9.985766e-01
Impact                                        -2.173450e-08
Major Problem                                 -2.227854e-08
Related Incidents                              4.119736e-09
Urgency                                        1.830408e-08
Incidents Count                                6.950308e-09
Duration Mean                                  5.333714e-02
Has Parent                                    -3.455071e-09
kmeans                                         5.409055e-07
pca                                            2.177902e-07
Business service_Communication Device         -1.729649e-08
Business service_Computer                      6.812673e-09
Business service_Database                      2.353892e-09
Business service_Network                       1.817635e-08
Business service_Other                         4.596233e-09
Business service_Scanner                

In [19]:
km = KMeans(n_clusters=8)
km.fit(transformed)
data['pca'] = km.labels_

In [24]:
metrics.adjusted_rand_score(y,data['pca'])

-0.02662341361869613

### Classify using Decision Tree

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)
tree_gini = DecisionTreeClassifier(criterion='gini',random_state=100, max_depth=5, min_samples_leaf=5)
tree_gini.fit(X_train, y_train)

In [ ]:
tree_entropy = DecisionTreeClassifier(criterion='entropy', random_state=100, max_depth=5, min_samples_leaf=5)
tree_entropy.fit(X_train, y_train)

In [ ]:
y_pred = tree_gini.predict(X_test)
y_pred

In [ ]:
y_pred_entropy = tree_entropy.predict(X_test)
y_pred_entropy

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
accuracy_score(y_test, y_pred_entropy)

In [ ]:
rf  = RandomForestClassifier(n_estimators = 1000, random_state=42)
rf.fit(X_train, y_train)

In [ ]:
pred = rf.predict(X_test)
pred

In [ ]:
accuracy_score(y_test, pred)